version: '2'
services:
  s-postgres:
    image: postgres:9.4-alpine
    hostname: host-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
       - network-docker
       
  s-flyway:
    image: dhoer/flyway:alpine
    build: flyway/
    entrypoint: /wait-for-start.sh s-postgres 5432
    command: >
      /bin/bash -c "
        nc -z s-postgres 5432 &&
        echo Connected to DB and started!
      "
    networks:
       - network-docker
    depends_on:
      - s-postgres
networks:
  network-docker:
    driver: bridge
