version: '2'
services:
  s-postgres:
    image: postgres:9.4-alpine
    build: postgres/
    hostname: host-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
       - network-docker
  s-flyway:
    image: dhoer/flyway:alpine
    build: flyway/
    command: -url=jdbc:postgresql://s-postgres:5432/postgres -baselineOnMigrate=true -schemas=public -user=postgres -password=postgres migrate
    entrypoint: /wait-for-it.sh s-postgres 5432 --timeout=0 --strict
    networks:
       - network-docker
    depends_on:
      - s-postgres
networks:
  network-docker:
    driver: bridge
