version: '2'
services:
   s-send:
      labels:
         NAME: send
      hostname: dockerhostsend
      command: docker network prune -f
      build: .
      ports:
      - 8088:8080
      - 8008:8000
      environment:
         JAVA_OPTS: null
         JPDA_ADDRESS: 8000
         JPDA_TRANSPORT: dt_socket
      networks:
      - network-docker
      restart: always
      
   rabbit:
      image: rabbitmq:3-management
      hostname: rabbit
      ports:
      - 5672:5672
      - 15672:15672
networks:
   network-docker:
      driver: bridge